services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: eagle
      POSTGRES_PASSWORD: eagle
      POSTGRES_DB: eaglebank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eagle -d eaglebank"]
      interval: 5s
      timeout: 3s
      retries: 10
